replicaCount: 1

image:
  repository: favourite-service
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8800

containerPort: 8800

readinessProbe:
  path: /favourite-service/actuator/health
  initialDelaySeconds: 30 
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6 

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
