fullnameOverride: payment-service

replicaCount: 1

image:
  repository: payment-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8400

readinessProbe:
  path: /payment-service/actuator/health
  port: 8400
  initialDelaySeconds: 30 
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6 

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
