fullnameOverride: cloud-config

replicaCount: 1

image:
  repository: cloud-config
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9296

readinessProbe:
  path: /actuator/health
  port: 9296
  initialDelaySeconds: 30 
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6 

env:
  - name: eureka.client.service-url.defaultZone
    value: http://discovery:8761/eureka
