apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-dashboard-root
  namespace: chaos-mesh
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #We need to disable SSL redirect to access the dashboard without SSL
    # well, it redirect http to https, so we need to disable it
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #Must be used in order to access the dashboard without SSL
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: chaos.lkdlas.icu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chaos-dashboard  # Initial dashboard service name
            port:
              number: 2333