fullnameOverride: order-service

replicaCount: 1

image:
  repository: order-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8300

readinessProbe:
  path: /order-service/actuator/health
  port: 8300
  initialDelaySeconds: 30 
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6 

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
