replicaCount: 1

image:
  repository: user-service
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8700

containerPort: 8700

readinessProbe:
  path: /user-service/actuator/health
  initialDelaySeconds: 30 
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6 

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev

