identityTrustAnchorsPEM: | 
  -----BEGIN CERTIFICATE-----
  MIIBjjCCATSgAwIBAgIRAMx2oOSvBtfEOEYQuiX9F3QwCgYIKoZIzj0EAwIwJTEj
  MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwNTI3MTUx
  NzA5WhcNMzUwNTI1MTUxNzA5WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
  c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABH11odv3GXlVMJjI
  I+1aR2Zh8DYMK0vzgu2hj/EbmQM/u7Z465/yNINaf3D8SQD274QWVliH51dNF1Om
  oiOeEA6jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
  A1UdDgQWBBQ5IAUH+0KjKyNl1TTA3L9ZeiQj3jAKBggqhkjOPQQDAgNIADBFAiBV
  Fyw1BP9E1eQFyiIQjI1yNHI13CN9bQ33OeaGSsabSgIhAMTMramsXLju8GaZobJF
  CDTOAOuk0WDYGlYD4sommVZS
  -----END CERTIFICATE-----
 
identity:
  issuer:
    tls:
      crtPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBszCCAVigAwIBAgIQeHxOV1Kkqf0c+bzPlVAojjAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNTA1MjcxNTE5
          MzhaFw0yNjA1MjcxNTE5MzhaMCkxJzAlBgNVBAMTHmlkZW50aXR5LmxpbmtlcmQu
          Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGOR+z+noiaU
          5rcD9ERsAMSQWgbYIiQvZpU5N4ugCpsmazoY7vxQAPiPWIoVeGZt+WdhP74hJQSD
          LM34frG6zn+jZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEA
          MB0GA1UdDgQWBBTfoffcy1chRf4jrXc7UGsaENlwLDAfBgNVHSMEGDAWgBQ5IAUH
          +0KjKyNl1TTA3L9ZeiQj3jAKBggqhkjOPQQDAgNJADBGAiEAmMP6OhKXtWe37tQC
          0HUC46aVFHtmVV0l3QHJAqn8hJMCIQCR1aYCM8sbLLido6rrnWC7fxjOZmxCMr7f
          M0I1ug8PoQ==
          -----END CERTIFICATE-----
      keyPEM: |          
          -----BEGIN EC PRIVATE KEY-----
          MHcCAQEEIEfU9U4fZ7YNfphSjsjmYQK/kaosfpXZ+RHcP2bpstLDoAoGCCqGSM49
          AwEHoUQDQgAEY5H7P6eiJpTmtwP0RGwAxJBaBtgiJC9mlTk3i6AKmyZrOhju/FAA
          +I9YihV4Zm35Z2E/viElBIMszfh+sbrOfw==
          -----END EC PRIVATE KEY-----