name: CI/CD Pipeline - Build and Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  
  call_deployment_workflow:
    name: Call Deployment Workflow
    
    uses: EcommerceDevops/workflows/.github/workflows/helmfile-sync.yml@main
    with:

      gke_cluster_name: 'staging-gke-cluster'
      gke_cluster_location: 'us-central1'
      environment: 'staging'

    secrets:

      GCP_SA_KEY: ${{ secrets.GCP_STAGING_ARQUISOFT }}
      GH_TOKEN: ${{ secrets.WORKFLOW_PAT_ADMIN }}