fullnameOverride: product-service

replicaCount: 1

image:
  repository: product-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8500

readinessProbe:
  path: /product-service/actuator/health
  port: 8500
  initialDelaySeconds: 30 
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6 

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
